# Generated by Django 5.2 on 2025-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_vendor_asset_sim_or_dongle_asset_dongle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('server', 'Server'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('network_switch', 'Network Switch'), ('firewall', 'Firewall'), ('router', 'Router'), ('sim_card', 'SIM Card'), ('phone', 'Phone'), ('camera', 'Camera')], default='laptop', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('pending', 'Pending'), ('available', 'Available')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='Unknown Vendor', max_length=255),
            preserve_default=False,
        ),
    ]
